# Cross-build Seek Doom for Anki Vector (ARM softfp / OE)
# Usage: make -f Makefile.vector

DOOM_SRC := ../third_party/doomgeneric/doomgeneric
BUILD   := build-vector
OUT     := seek-doom

ifndef CROSS
CROSS := /workspace/poky/build/tmp-glibc/sysroots-components/x86_64/gcc-cross-arm/usr/bin/arm-oe-linux-gnueabi/arm-oe-linux-gnueabi-
endif

ifndef SYSROOT
SYSROOT := /workspace/poky/build/tmp-glibc/work/armv7a-neon-vfpv4-oe-linux-gnueabi/alsa-lib/1.2.14/recipe-sysroot
endif

CC      := $(CROSS)gcc
CFLAGS  := -O2 -DNORMALUNIX -DLINUX -D_DEFAULT_SOURCE -DFEATURE_SOUND \
	-DDOOMGENERIC_RESX=320 -DDOOMGENERIC_RESY=200 \
	-march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=softfp \
	-B/tmp/arm-cross-wrap/ \
	--sysroot=$(SYSROOT) -I$(DOOM_SRC) -Istubs
LDFLAGS := --sysroot=$(SYSROOT) -Wl,--gc-sections \
	-march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=softfp \
	-B/tmp/arm-cross-wrap/
LIBS    := -lm

SRC_DOOM := dummy.c am_map.c doomdef.c doomstat.c dstrings.c d_event.c d_items.c \
	d_iwad.c d_loop.c d_main.c d_mode.c d_net.c f_finale.c f_wipe.c g_game.c \
	hu_lib.c hu_stuff.c info.c i_cdmus.c i_endoom.c i_joystick.c i_scale.c \
	i_sound.c i_system.c i_timer.c memio.c m_argv.c m_bbox.c m_cheat.c \
	m_config.c m_controls.c m_fixed.c m_menu.c m_misc.c m_random.c \
	p_ceilng.c p_doors.c p_enemy.c p_floor.c p_inter.c p_lights.c p_map.c \
	p_maputl.c p_mobj.c p_plats.c p_pspr.c p_saveg.c p_setup.c p_sight.c \
	p_spec.c p_switch.c p_telept.c p_tick.c p_user.c r_bsp.c r_data.c \
	r_draw.c r_main.c r_plane.c r_segs.c r_sky.c r_things.c sha1.c sounds.c \
	statdump.c st_lib.c st_stuff.c s_sound.c tables.c v_video.c wi_stuff.c \
	w_checksum.c w_file.c w_main.c w_wad.c z_zone.c w_file_stdc.c i_input.c \
	i_video.c doomgeneric.c

OBJS := $(addprefix $(BUILD)/,$(SRC_DOOM:.c=.o)) \
	$(BUILD)/doomgeneric_vector.o \
	$(BUILD)/i_vectorsound.o

.PHONY: all clean

all: $(OUT)

$(BUILD):
	mkdir -p $(BUILD)

$(BUILD)/%.o: $(DOOM_SRC)/%.c | $(BUILD)
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD)/doomgeneric_vector.o: doomgeneric_vector.c | $(BUILD)
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD)/i_vectorsound.o: i_vectorsound.c | $(BUILD)
	$(CC) $(CFLAGS) -c $< -o $@

$(OUT): $(OBJS)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)
	$(CROSS)strip $@ || true
	@echo "Built $@"
	@$(CROSS)size $@ || true

clean:
	rm -rf $(BUILD) $(OUT)
